### ISSUE TITLE
urljoin?

### ISSUE THREAD

**Issue by chick0** [KokoseiJ/NicoBot#4]
![Screenshot](https://user-images.githubusercontent.com/64462443/129662350-c5cdc802-985f-4749-b909-8db70b723759.png)

```python
from urllib.parse import urljoin
from urllib.request import Request, urlopen
```

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin

**Comment by KokoseiJ** [comment]
fixed by commit b4842aa
